name: Monitor Website Console Logs

on:
  schedule:
    - cron: "*/5 * * * *" # Run every 5 minutes
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  monitor-console:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Monitor Console Logs
        run: |
          node checkConsoleLogs.js
        env:
          TARGET_URL: "https://edit-bossz.github.io/My-Website/"
          CHECK_TEXT: "Response from server: Data recorded"
